config:
  target: https://google.com
  phases:
    - duration: 5      # La fase dura 5 segundos
      arrivalRate: 1    # Comienza con 1 usuarios virtuales por segundo
      rampTo: 3        # Y gradualmente aumenta hasta 3 usuarios por segundo
  engines:
    playwright: {}
  processor: "../../src/performance-test/load-test-processor.ts"
scenarios:
  - engine: playwright
    flowFunction: "googleSearch"
    flow: []
